services:
  drupal:
    image: drupal:11.3-php8.5-apache
    ports:
      - "42090:80"
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    environment:
      - DRUPAL_DB_HOST=${DRUPAL_DB_HOST}
      - DRUPAL_DB_NAME=${DRUPAL_DB_NAME}
      - DRUPAL_DB_USER=${DRUPAL_DB_USER}
      - DRUPAL_DB_PASSWORD=${DRUPAL_DB_PASSWORD}
  db:
    image: mariadb:latest
    ports:
      - "3307:3306"
    env_file:
      - .env
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DRUPAL_DB_NAME}
      - MARIADB_USER=${DRUPAL_DB_USER}
      - MARIADB_PASSWORD=${DRUPAL_DB_PASSWORD}